<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function findRandom()
    {
        $qb = $this->createQueryBuilder('p')
            ->getQuery();

        $quotes = $qb->getResult();
        shuffle($quotes);

        return $quotes[0];
    }
}
